"""
Query routes — Student endpoints for the hybrid VideoRAG system.

Endpoints:
    POST /ask       — Submit a question → 3-part response (text + clip + timestamp)
    GET  /clip/{id} — Download/stream an extracted video clip
"""

from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse

from app.api.dependencies import get_current_user
import json
from app.models.schemas import QueryRequest, QueryResponse, AnswerInfo, VideoClipInfo, TimestampInfo
from app.models.database import ChatMessage
from app.services.query_service import process_query
from app.config import settings
from database.connection import get_db
from sqlalchemy.orm import Session

router = APIRouter()


@router.post("/ask", response_model=QueryResponse)
async def ask_question(
    request: QueryRequest,
    current_user=Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Submit a natural language question about lecture content.
    Dynamically persists conversation in the chat_messages database table.

    The hybrid pipeline:
    1. Searches text metadata to find relevant timestamps (cheap)
    2. Extracts a video clip at those timestamps
    3. Sends the clip to a Multimodal LLM for deep analysis

    Returns a 3-part response:
    - Text answer with confidence level
    - Video clip URL for playback/download
    - Timestamps in the source video
    """
    try:
        user_id = current_user.get("id") if isinstance(current_user, dict) else getattr(current_user, "id", None)

        # 1. Dynamically save user's question
        if user_id:
            user_msg = ChatMessage(
                user_id=user_id,
                role="user",
                content=request.question,
            )
            db.add(user_msg)
            db.commit()

        result = await process_query(request.question, current_user)

        answer_data = result.get("answer", {"text": "No answer generated."})
        clip_data = result.get("video_clip", {})
        timestamp_data = result.get("timestamp", {})
        sources_data = result.get("sources", [])

        # 2. Dynamically save AI assistant response
        if user_id:
            assistant_msg = ChatMessage(
                user_id=user_id,
                role="assistant",
                content=answer_data.get("text", ""),
                sources=json.dumps(sources_data) if sources_data else None,
                video_timestamp=timestamp_data.get("start_time"),
                confidence=answer_data.get("confidence", "high"),
            )
            db.add(assistant_msg)
            db.commit()

        return QueryResponse(
            answer=AnswerInfo(**answer_data),
            video_clip=VideoClipInfo(**clip_data),
            timestamp=TimestampInfo(**timestamp_data),
            sources=sources_data,
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error processing query: {str(e)}",
        )


@router.get("/clip/{clip_id}")
async def get_clip(
    clip_id: str,
    current_user=Depends(get_current_user),
):
    """
    Download or stream an extracted video clip by clip ID.

    The clip was generated by Step 3 of the hybrid pipeline.
    """
    clips_dir = Path(settings.CLIP_OUTPUT_DIR)
    clip_path = clips_dir / f"clip_{clip_id}.mp4"

    if not clip_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Clip '{clip_id}' not found",
        )

    return FileResponse(
        path=str(clip_path),
        media_type="video/mp4",
        filename=f"clip_{clip_id}.mp4",
    )
