"""
Query routes — Student endpoints for the hybrid VideoRAG system.

Endpoints:
    POST /ask       — Submit a question → 3-part response (text + clip + timestamp)
    GET  /clip/{id} — Download/stream an extracted video clip
"""

from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse

from app.api.dependencies import get_current_user
from app.models.schemas import QueryRequest, QueryResponse, AnswerInfo, VideoClipInfo, TimestampInfo
from app.services.query_service import process_query
from app.config import settings

router = APIRouter()


@router.post("/ask", response_model=QueryResponse)
async def ask_question(
    request: QueryRequest,
    current_user=Depends(get_current_user),
):
    """
    Submit a natural language question about lecture content.

    The hybrid pipeline:
    1. Searches text metadata to find relevant timestamps (cheap)
    2. Extracts a video clip at those timestamps
    3. Sends the clip to a Multimodal LLM for deep analysis

    Returns a 3-part response:
    - Text answer with confidence level
    - Video clip URL for playback/download
    - Timestamps in the source video
    """
    try:
        result = await process_query(request.question, current_user)

        return QueryResponse(
            answer=AnswerInfo(**result.get("answer", {"text": "No answer generated."})),
            video_clip=VideoClipInfo(**result.get("video_clip", {})),
            timestamp=TimestampInfo(**result.get("timestamp", {})),
            sources=result.get("sources", []),
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error processing query: {str(e)}",
        )


@router.get("/clip/{clip_id}")
async def get_clip(
    clip_id: str,
    current_user=Depends(get_current_user),
):
    """
    Download or stream an extracted video clip by clip ID.

    The clip was generated by Step 3 of the hybrid pipeline.
    """
    clips_dir = Path(settings.CLIP_OUTPUT_DIR)
    clip_path = clips_dir / f"clip_{clip_id}.mp4"

    if not clip_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Clip '{clip_id}' not found",
        )

    return FileResponse(
        path=str(clip_path),
        media_type="video/mp4",
        filename=f"clip_{clip_id}.mp4",
    )
